# noinspection PyArgumentList

def build_mapping(data):
    def val(key):
        return data[key] if key in data else ""

    record = {
        "pri_id": val(data, "pri_id"),
        "tid": val(data, "tid"),
        "Id": val(data, "Id"),
        "OwnerId": val(data, "OwnerId"),
        "IsDeleted": val(data, "IsDeleted"),
        "Name": val(data, "Name"),
        "CreatedDate": val(data, "CreatedDate"),
        "CreatedById": val(data, "CreatedById"),
        "LastModifiedDate": val(data, "LastModifiedDate"),
        "LastModifiedById": val(data, "LastModifiedById"),
        "SystemModstamp": val(data, "SystemModstamp"),
        "LastActivityDate": val(data, "LastActivityDate"),
        "Branch_Name__c": val(data, "Branch_Name__c"),
        "Contact__c": val(data, "Contact__c"),
        "Customer_Number__c": val(data, "Customer_Number__c"),
        "Customer__c": val(data, "Customer__c"),
        "Invoice_Amount__c": val(data, "Invoice_Amount__c"),
        "Invoice_Date__c": val(data, "Invoice_Date__c"),
        "Bill_Date__c": val(data, "Bill_Date__c"),
        "customer_mobile__c": val(data, "customer_mobile__c"),
        "customerId": val(data, "customerId"),
        "Customer_Last_Name__c": val(data, "Customer_Last_Name__c"),
        "Customer_Name__c": val(data, "Customer_Name__c"),
        "item_cgst_perc": val(data, "item_cgst_perc"),
        "item_sgst_perc": val(data, "item_sgst_perc"),
        "item_sgst": val(data, "item_sgst"),
        "item_igst_perc": val(data, "item_igst_perc"),
        "item_cgst": val(data, "item_cgst"),
        "item_igst": val(data, "item_igst"),
        "Deptid": val(data, "Deptid"),
        "billed_at_branch_name": val(data, "billed_at_branch_name"),
        "billed_at_company_name": val(data, "billed_at_company_name"),
        "billed_at_address": val(data, "billed_at_address"),
        "billed_at_city": val(data, "billed_at_city"),
        "billed_at_state": val(data, "billed_at_state"),
        "billed_at_phone_no1": val(data, "billed_at_phone_no1"),
        "billed_at_phone_no2": val(data, "billed_at_phone_no2"),
        "billed_at_GSTN_no": val(data, "billed_at_GSTN_no"),
        "billed_at_VAT_no": val(data, "billed_at_VAT_no"),
        "billed_at_state_code": val(data, "billed_at_state_code"),
        "billed_at_PAN_no": val(data, "billed_at_PAN_no"),
        "delivery_from_branch_name": val(data, "delivery_from_branch_name"),
        "delivery_from_company_name": val(data, "delivery_from_company_name"),
        "delivery_from_address": val(data, "delivery_from_address"),
        "delivery_from_city": val(data, "delivery_from_city"),
        "delivery_from_state": val(data, "delivery_from_state"),
        "delivery_from_phone_no1": val(data, "delivery_from_phone_no1"),
        "delivery_from_phone_no2": val(data, "delivery_from_phone_no2"),
        "delivery_from_GSTN_no": val(data, "delivery_from_GSTN_no"),
        "delivery_from_VAT_no": val(data, "delivery_from_VAT_no"),
        "delivery_from_state_code": val(data, "delivery_from_state_code"),
        "delivery_from_PAN_no": val(data, "delivery_from_PAN_no"),
        "customer_state_code": val(data, "customer_state_code"),
        "Email__c": val(data, "Email__c"),
        "IMEINumber__c": val(data, "IMEINumber__c"),
        "Item_Brand_Name__c": val(data, "Item_Brand_Name__c"),
        "Item_Code__c": val(data, "Item_Code__c"),
        "Item_Group_Name__c": val(data, "Item_Group_Name__c"),
        "Item_Name__c": val(data, "Item_Name__c"),
        "Item_Rate__c": val(data, "Item_Rate__c"),
        "Item_Remarks__c": val(data, "Item_Remarks__c"),
        "Location__c": val(data, "Location__c"),
        "Product__c": val(data, "Product__c"),
        "Products__c": val(data, "Products__c"),
        "PurchasedDate__c": val(data, "PurchasedDate__c"),
        "Service_Center__c": val(data, "Service_Center__c"),
        "Showroom__c": val(data, "Showroom__c"),
        "Showroom_code__c": val(data, "Showroom_code__c"),
        "Status__c": val(data, "Status__c"),
        "bill_cancel_against__c": val(data, "bill_cancel_against__c"),
        "bill_cancel_amount__c": val(data, "bill_cancel_amount"),
        "bill_cancel_date__c": val(data, "bill_cancel_date__c"),
        "bill_cancel_reason__c": val(data, "bill_cancel_reason__c"),
        "bill_cancel_time__c": val(data, "bill_cancel_time__c"),
        "bill_discount__c": val(data, "bill_discount__c"),
        "bill_discount_per__c": val(data, "bill_discount_per__c"),
        "bill_grand_total__c": val(data, "bill_grand_total__c"),
        "bill_gross_amount__c": val(data, "bill_gross_amount__c"),
        "bill_modify__c": val(data, "bill_modify__c"),
        "bill_modify_datetime__c": val(data, "bill_modify_datetime__c"),
        "bill_modify_reason__c": val(data, "bill_modify_reason__c"),
        "bill_net_amount__c": val(data, "bill_net_amount__c"),
        "bill_remarks1__c": val(data, "bill_remarks1__c"),
        "bill_remarks3__c": val(data, "bill_remarks3__c"),
        "bill_remarks4__c": val(data, "bill_remarks4__c"),
        "bill_remarks5__c": val(data, "bill_remarks5__c"),
        "bill_round_off_amount__c": val(data, "bill_round_off_amount__c"),
        "bill_service_tax__c": val(data, "bill_service_tax__c"),
        "bill_status__c": val(data, "bill_status__c"),
        "bill_tax__c": val(data, "bill_tax__c"),
        "bill_tender_type__c": val(data, "bill_tender_type__c"),
        "bill_time__c": val(data, "bill_time__c"),
        "bill_transaction_no__c": val(data, "bill_transaction_no__c"),
        "bill_transaction_type__c": val(data, "bill_transaction_type__c"),
        "bill_type__c": val(data, "bill_type__c"),
        "customer_address__c": val(data, "customer_address__c"),
        "customer_area__c": val(data, "customer_area__c"),
        "customer_city__c": val(data, "customer_city__c"),
        "customer_doa__c": val(data, "customer_doa__c"),
        "customer_dob__c": val(data, "customer_dob__c"),
        "customer_email__c": val(data, "customer_email__c"),
        "customer_fname__c": val(data, "customer_fname__c"),
        "customer_gender__c": val(data, "customer_gender__c"),
        "customer_lname__c": val(data, "customer_lname__c"),
        "customer_remarks1__c": val(data, "customer_remarks1__c"),
        "customer_remarks2__c": val(data, "customer_remarks2__c"),
        "customer_remarks3__c": val(data, "customer_remarks3__c"),
        "customer_remarks4__c": val(data, "customer_remarks4__c"),
        "customer_remarks5__c": val(data, "customer_remarks5__c"),
        "customer_state__c": val(data, "customer_state__c"),
        "ext_param1__c": val(data, "ext_param1__c"),
        "ext_param2__c": val(data, "ext_param2__c"),
        "ext_param3__c": val(data, "ext_param3__c"),
        "ext_param4__c": val(data, "ext_param4__c"),
        "ext_param5__c": val(data, "ext_param5__c"),
        "item_barcode__c": val(data, "item_barcode__c"),
        "item_brand_code__c": val(data, "item_brand_code__c"),
        "item_category_code__c": val(data, "item_category_code__c"),
        "item_category_name__c": val(data, "item_category_name__c"),
        "item_color_code__c": val(data, "item_color_code__c"),
        "item_color_name__c": val(data, "item_color_name__c"),
        "item_department_code__c": val(data, "item_department_code__c"),
        "item_department_name__c": val(data, "item_department_name__c"),
        "item_discount__c": val(data, "item_discount__c"),
        "item_discount_per__c": val(data, "item_discount_per__c"),
        "item_gross_amount__c": val(data, "item_gross_amount__c"),
        "item_group__c": val(data, "item_group__c"),
        "item_net_amount__c": val(data, "item_net_amount__c"),
        "item_quantity__c": val(data, "item_quantity__c"),
        "item_remarks2__c": val(data, "item_remarks2__c"),
        "item_remarks3__c": val(data, "item_remarks3__c"),
        "item_remarks4__c": val(data, "item_remarks4__c"),
        "item_remarks5__c": val(data, "item_remarks5__c"),
        "item_serial_no__c": val(data, "item_serial_no__c"),
        "item_service_tax__c": val(data, "item_service_tax__c"),
        "item_size_code__c": val(data, "item_size_code__c"),
        "item_size_name__c": val(data, "item_size_name__c"),
        "item_status__c": val(data, "item_status__c"),
        "item_sub_category_code__c": val(data, "item_sub_category_code__c"),
        "item_sub_category_name__c": val(data, "item_sub_category_name__c"),
        "item_tax__c": val(data, "item_tax__c"),
        "store_code__c": val(data, "store_code__c"),
        "voucher_code__c": val(data, "voucher_code__c"),
        "voucher_type__c": val(data, "voucher_type__c"),
        "voucher_value__c": val(data, "voucher_value__c"),
        "Docid__c": val(data, "Docid__c"),
        "Customer_Address_New__c": val(data, "Customer_Address_New__c"),
        "customer_mobile__c_backup": val(data, "customer_mobile__c_backup"),
        "billed_at_addressline2": val(data, "billed_at_addressline2"),
        "billed_at_addressline3": val(data, "billed_at_addressline3"),
        "billed_at_pincode": val(data, "billed_at_pincode"),
        "delivery_from_branch_store_code": val(data, "delivery_from_branch_store_code"),
        "delivery_from_addressline2": val(data, "delivery_from_addressline2"),
        "delivery_from_addressline3": val(data, "delivery_from_addressline3"),
        "bill_refference_no": val(data, "bill_refference_no"),
        "bill_refference_date": val(data, "bill_refference_date"),
        "bill_total_trade_deduction": val(data, "bill_total_trade_deduction"),
        "bill_total_trade_addition": val(data, "bill_total_trade_addition"),
        "customer_addressline2": val(data, "customer_addressline2"),
        "customer_addressline3": val(data, "customer_addressline3"),
        "customer_pincode": val(data, "customer_pincode"),
        "customer_GSTN_no": val(data, "customer_GSTN_no"),
        "customer_PAN_no": val(data, "customer_PAN_no"),
        "customer_state": val(data, "customer_state"),
        "delivery_to_Name": val(data, "delivery_to_Name"),
        "delivery_to_addressline1": val(data, "delivery_to_addressline1"),
        "delivery_to_addressline2": val(data, "delivery_to_addressline2"),
        "delivery_to_addressline3": val(data, "delivery_to_addressline3"),
        "delivery_to_city": val(data, "delivery_to_city"),
        "delivery_to_state": val(data, "delivery_to_state"),
        "delivery_to_pincode": val(data, "delivery_to_pincode"),
        "delivery_to_phone_no1": val(data, "delivery_to_phone_no1"),
        "delivery_to_phone_no2": val(data, "delivery_to_phone_no2"),
        "delivery_to_GSTN_no": val(data, "delivery_to_GSTN_no"),
        "delivery_to_state_code": val(data, "delivery_to_state_code"),
        "delivery_to_PAN_no": val(data, "delivery_to_PAN_no"),
        "item_sno": val(data, "item_sno"),
        "item_name": val(data, "item_name"),
        "item_gross_rate": val(data, "item_gross_rate"),
        "item_taxable_Amount": val(data, "item_taxable_Amount"),
        "item_brand_name": val(data, "item_brand_name"),
        "item_product_name": val(data, "item_product_name"),
        "customer_phone_no2": val(data, "customer_phone_no2"),
        "updated_At": val(data, "updated_At"),
        "cusId_error": val(data, "cusId_error"),
        "customer_mobile__c2": val(data, "customer_mobile__c2"),
        "Bill_No__c": val(data, "Bill_No__c"),
        "Customer_Code_New": val(data, "Customer_Code_New"),
        "bill_modify_date": val(data, "bill_modify_date"),
        "bill_modify_time": val(data, "bill_modify_time"),
        "Customer_Code__c_new": val(data, "Customer_Code__c_new"),
        "Customer_Code__c": val(data, "Customer_Code__c"),
        "bill_remarks2": val(data, "bill_remarks2"),
        "bill_remarks2__c": val(data, "bill_remarks2__c"),
        "item_remarks1__c": val(data, "item_remarks1__c"),
        "Bill_Grant_Total__c": val(data, "Bill_Grant_Total__c"),
        "ageOfDevice": val(data, "ageOfDevice"),
        "emp_id": val(data, "emp_id"),
        "emp_name": val(data, "emp_name"),
    }

    return record


Missing = [
           'bill_item_gross_amount',
           'bill_item_net_amount',
           'bill_item_total_discount',
           'bill_item_total_tax',
           'bill_transcation_no',
           'billed_at_addressline1',
           'customer_addressline1',
           'customer_phone_no1',
           'delivery_from_addressline1',
           'item_discount1',
           'item_discount2',
           'item_inctax_rate',
]



def get_missed_map(record, mapped):
    missed_map = {}

    for key in record.keys():
        if key not in mapped:
            missed_map[key] = record[key]

    return missed_map

