def record_mapping(data):
    record = {
        "pri_id": data.get("pri_id", ""),
        "tid": data.get("tid", ""),
        "Id": data.get("Id", ""),
        "OwnerId": data.get("OwnerId", ""),
        "IsDeleted": data.get("IsDeleted", ""),
        "Name": data.get("Name", ""),
        "CreatedDate": data.get("CreatedDate", ""),
        "CreatedById": data.get("CreatedById", ""),
        "LastModifiedDate": data.get("LastModifiedDate", ""),
        "LastModifiedById": data.get("LastModifiedById", ""),
        "SystemModstamp": data.get("SystemModstamp", ""),
        "LastActivityDate": data.get("LastActivityDate", ""),
        "Branch_Name__c": data.get("Branch_Name__c", ""),
        "Contact__c": data.get("Contact__c", ""),
        "Customer_Number__c": data.get("Customer_Number__c", ""),
        "Customer__c": data.get("Customer__c", ""),
        "Invoice_Amount__c": data.get("Invoice_Amount__c", ""),
        "Invoice_Date__c": data.get("Invoice_Date__c", ""),
        "Bill_Date__c": data.get("Bill_Date__c", ""),
        "customer_mobile__c": data.get("customer_mobile__c", ""),
        "customerId": data.get("customerId", ""),
        "Customer_Last_Name__c": data.get("Customer_Last_Name__c", ""),
        "Customer_Name__c": data.get("Customer_Name__c", ""),
        "item_cgst_perc": data.get("item_cgst_perc", ""),
        "item_sgst_perc": data.get("item_sgst_perc", ""),
        "item_sgst": data.get("item_sgst", ""),
        "item_igst_perc": data.get("item_igst_perc", ""),
        "item_cgst": data.get("item_cgst", ""),
        "item_igst": data.get("item_igst", ""),
        "Deptid": data.get("Deptid", ""),
        "billed_at_branch_name": data.get("billed_at_branch_name", ""),
        "billed_at_company_name": data.get("billed_at_company_name", ""),
        "billed_at_address": data.get("billed_at_address", ""),
        "billed_at_city": data.get("billed_at_city", ""),
        "billed_at_state": data.get("billed_at_state", ""),
        "billed_at_phone_no1": data.get("billed_at_phone_no1", ""),
        "billed_at_phone_no2": data.get("billed_at_phone_no2", ""),
        "billed_at_GSTN_no": data.get("billed_at_GSTN_no", ""),
        "billed_at_VAT_no": data.get("billed_at_VAT_no", ""),
        "billed_at_state_code": data.get("billed_at_state_code", ""),
        "billed_at_PAN_no": data.get("billed_at_PAN_no", ""),
        "delivery_from_branch_name": data.get("delivery_from_branch_name", ""),
        "delivery_from_company_name": data.get("delivery_from_company_name", ""),
        "delivery_from_address": data.get("delivery_from_address", ""),
        "delivery_from_city": data.get("delivery_from_city", ""),
        "delivery_from_state": data.get("delivery_from_state", ""),
        "delivery_from_phone_no1": data.get("delivery_from_phone_no1", ""),
        "delivery_from_phone_no2": data.get("delivery_from_phone_no2", ""),
        "delivery_from_GSTN_no": data.get("delivery_from_GSTN_no", ""),
        "delivery_from_VAT_no": data.get("delivery_from_VAT_no", ""),
        "delivery_from_state_code": data.get("delivery_from_state_code", ""),
        "delivery_from_PAN_no": data.get("delivery_from_PAN_no", ""),
        "customer_state_code": data.get("customer_state_code", ""),
        "Email__c": data.get("Email__c", ""),
        "IMEINumber__c": data.get("IMEINumber__c", ""),
        "Item_Brand_Name__c": data.get("Item_Brand_Name__c", ""),
        "Item_Code__c": data.get("Item_Code__c", ""),
        "Item_Group_Name__c": data.get("Item_Group_Name__c", ""),
        "Item_Name__c": data.get("Item_Name__c", ""),
        "Item_Rate__c": data.get("Item_Rate__c", ""),
        "Item_Remarks__c": data.get("Item_Remarks__c", ""),
        "Location__c": data.get("Location__c", ""),
        "Product__c": data.get("Product__c", ""),
        "Products__c": data.get("Products__c", ""),
        "PurchasedDate__c": data.get("PurchasedDate__c", ""),
        "Service_Center__c": data.get("Service_Center__c", ""),
        "Showroom__c": data.get("Showroom__c", ""),
        "Showroom_code__c": data.get("Showroom_code__c", ""),
        "Status__c": data.get("Status__c", ""),
        "bill_cancel_against__c": data.get("bill_cancel_against__c", ""),
        "bill_cancel_amount": data.get("bill_cancel_amount", ""),
        "bill_cancel_date__c": data.get("bill_cancel_date__c", ""),
        "bill_cancel_reason__c": data.get("bill_cancel_reason__c", ""),
        "bill_cancel_time__c": data.get("bill_cancel_time__c", ""),
        "bill_discount__c": data.get("bill_discount__c", ""),
        "bill_discount_per__c": data.get("bill_discount_per__c", ""),
        "bill_grand_total__c": data.get("bill_grand_total__c", ""),
        "bill_gross_amount__c": data.get("bill_gross_amount__c", ""),
        "bill_modify__c": data.get("bill_modify__c", ""),
        "bill_modify_datetime__c": data.get("bill_modify_datetime__c", ""),
        "bill_modify_reason__c": data.get("bill_modify_reason__c", ""),
        "bill_net_amount__c": data.get("bill_net_amount__c", ""),
        "bill_remarks1__c": data.get("bill_remarks1__c", ""),
        "bill_remarks3__c": data.get("bill_remarks3__c", ""),
        "bill_remarks4__c": data.get("bill_remarks4__c", ""),
        "bill_remarks5__c": data.get("bill_remarks5__c", ""),
        "bill_round_off_amount__c": data.get("bill_round_off_amount__c", ""),
        "bill_service_tax__c": data.get("bill_service_tax__c", ""),
        "bill_status__c": data.get("bill_status__c", ""),
        "bill_tax__c": data.get("bill_tax__c", ""),
        "bill_tender_type__c": data.get("bill_tender_type__c", ""),
        "bill_time__c": data.get("bill_time__c", ""),
        "bill_transaction_no__c": data.get("bill_transaction_no__c", ""),
        "bill_transaction_type__c": data.get("bill_transaction_type__c", ""),
        "bill_type__c": data.get("bill_type__c", ""),
        "customer_address__c": data.get("customer_address__c", ""),
        "customer_area__c": data.get("customer_area__c", ""),
        "customer_city__c": data.get("customer_city__c", ""),
        "customer_doa__c": data.get("customer_doa__c", ""),
        "customer_dob__c": data.get("customer_dob__c", ""),
        "customer_email__c": data.get("customer_email__c", ""),
        "customer_fname__c": data.get("customer_fname__c", ""),
        "customer_gender__c": data.get("customer_gender__c", ""),
        "customer_lname__c": data.get("customer_lname__c", ""),
        "customer_remarks1__c": data.get("customer_remarks1__c", ""),
        "customer_remarks2__c": data.get("customer_remarks2__c", ""),
        "customer_remarks3__c": data.get("customer_remarks3__c", ""),
        "customer_remarks4__c": data.get("customer_remarks4__c", ""),
        "customer_remarks5__c": data.get("customer_remarks5__c", ""),
        "customer_state__c": data.get("customer_state__c", ""),
        "ext_param1__c": data.get("ext_param1__c", ""),
        "ext_param2__c": data.get("ext_param2__c", ""),
        "ext_param3__c": data.get("ext_param3__c", ""),
        "ext_param4__c": data.get("ext_param4__c", ""),
        "ext_param5__c": data.get("ext_param5__c", ""),
        "item_barcode__c": data.get("item_barcode__c", ""),
        "item_brand_code__c": data.get("item_brand_code__c", ""),
        "item_category_code__c": data.get("item_category_code__c", ""),
        "item_category_name__c": data.get("item_category_name__c", ""),
        "item_color_code__c": data.get("item_color_code__c", ""),
        "item_color_name__c": data.get("item_color_name__c", ""),
        "item_department_code__c": data.get("item_department_code__c", ""),
        "item_department_name__c": data.get("item_department_name__c", ""),
        "item_discount__c": data.get("item_discount__c", ""),
        "item_discount_per__c": data.get("item_discount_per__c", ""),
        "item_gross_amount__c": data.get("item_gross_amount__c", ""),
        "item_group__c": data.get("item_group__c", ""),
        "item_net_amount__c": data.get("item_net_amount__c", ""),
        "item_quantity__c": data.get("item_quantity__c", ""),
        "item_remarks2__c": data.get("item_remarks2__c", ""),
        "item_remarks3__c": data.get("item_remarks3__c", ""),
        "item_remarks4__c": data.get("item_remarks4__c", ""),
        "item_remarks5__c": data.get("item_remarks5__c", ""),
        "item_serial_no__c": data.get("item_serial_no__c", ""),
        "item_service_tax__c": data.get("item_service_tax__c", ""),
        "item_size_code__c": data.get("item_size_code__c", ""),
        "item_size_name__c": data.get("item_size_name__c", ""),
        "item_status__c": data.get("item_status__c", ""),
        "item_sub_category_code__c": data.get("item_sub_category_code__c", ""),
        "item_sub_category_name__c": data.get("item_sub_category_name__c", ""),
        "item_tax__c": data.get("item_tax__c", ""),
        "store_code__c": data.get("store_code__c", ""),
        "voucher_code__c": data.get("voucher_code__c", ""),
        "voucher_type__c": data.get("voucher_type__c", ""),
        "voucher_value__c": data.get("voucher_value__c", ""),
        "Docid__c": data.get("Docid__c", ""),
        "Customer_Address_New__c": data.get("Customer_Address_New__c", ""),
        "customer_mobile__c_backup": data.get("customer_mobile__c_backup", ""),
        "billed_at_addressline2": data.get("billed_at_addressline2", ""),
        "billed_at_addressline3": data.get("billed_at_addressline3", ""),
        "billed_at_pincode": data.get("billed_at_pincode", ""),
        "delivery_from_branch_store_code": data.get("delivery_from_branch_store_code", ""),
        "delivery_from_addressline2": data.get("delivery_from_addressline2", ""),
        "delivery_from_addressline3": data.get("delivery_from_addressline3", ""),
        "bill_refference_no": data.get("bill_refference_no", ""),
        "bill_refference_date": data.get("bill_refference_date", ""),
        "bill_total_trade_deduction": data.get("bill_total_trade_deduction", ""),
        "bill_total_trade_addition": data.get("bill_total_trade_addition", ""),
        "customer_addressline2": data.get("customer_addressline2", ""),
        "customer_addressline3": data.get("customer_addressline3", ""),
        "customer_pincode": data.get("customer_pincode", ""),
        "customer_GSTN_no": data.get("customer_GSTN_no", ""),
        "customer_PAN_no": data.get("customer_PAN_no", ""),
        "customer_state": data.get("customer_state", ""),
        "delivery_to_Name": data.get("delivery_to_Name", ""),
        "delivery_to_addressline1": data.get("delivery_to_addressline1", ""),
        "delivery_to_addressline2": data.get("delivery_to_addressline2", ""),
        "delivery_to_addressline3": data.get("delivery_to_addressline3", ""),
        "delivery_to_city": data.get("delivery_to_city", ""),
        "delivery_to_state": data.get("delivery_to_state", ""),
        "delivery_to_pincode": data.get("delivery_to_pincode", ""),
        "delivery_to_phone_no1": data.get("delivery_to_phone_no1", ""),
        "delivery_to_phone_no2": data.get("delivery_to_phone_no2", ""),
        "delivery_to_GSTN_no": data.get("delivery_to_GSTN_no", ""),
        "delivery_to_state_code": data.get("delivery_to_state_code", ""),
        "delivery_to_PAN_no": data.get("delivery_to_PAN_no", ""),
        "item_sno": data.get("item_sno", ""),
        "item_name": data.get("item_name", ""),
        "item_gross_rate": data.get("item_gross_rate", ""),
        "item_taxable_Amount": data.get("item_taxable_Amount", ""),
        "item_brand_name": data.get("item_brand_name", ""),
        "item_product_name": data.get("item_product_name", ""),
        "customer_phone_no2": data.get("customer_phone_no2", ""),
        "updated_At": data.get("updated_At", ""),
        "cusId_error": data.get("cusId_error", ""),
        "customer_mobile__c2": data.get("customer_mobile__c2", ""),
        "Bill_No__c": data.get("Bill_No__c", ""),
        "Customer_Code_New": data.get("Customer_Code_New", ""),
        "bill_modify_date": data.get("bill_modify_date", ""),
        "bill_modify_time": data.get("bill_modify_time", ""),
        "Customer_Code__c_new": data.get("Customer_Code__c_new", ""),
        "Customer_Code__c": data.get("Customer_Code__c", ""),
        "bill_remarks2": data.get("bill_remarks2", ""),
        "bill_remarks2__c": data.get("bill_remarks2__c", ""),
        "item_remarks1__c": data.get("item_remarks1__c", ""),
        "Bill_Grant_Total__c": data.get("Bill_Grant_Total__c", ""),
        "ageOfDevice": data.get("ageOfDevice", ""),
        "emp_id": data.get("emp_id", ""),
        "emp_name": data.get("emp_name", ""),
    }

    return record

def up_mapping(data):
    mapped = {
        "bill_modify_date": data.get("bill_modify_date", ""),
        "bill_modify_time": data.get("bill_modify_time", ""),
        "bill_refference_date": data.get("bill_refference_date", ""),
        "bill_refference_no": data.get("bill_refference_no", ""),
        "bill_remarks2": data.get("bill_remarks2", ""),
        "bill_total_trade_addition": data.get("bill_total_trade_addition", ""),
        "bill_total_trade_deduction": data.get("bill_total_trade_deduction", ""),
        "billed_at_GSTN_no": data.get("billed_at_GSTN_no", ""),
        "billed_at_PAN_no": data.get("billed_at_PAN_no", ""),
        "billed_at_addressline2": data.get("billed_at_addressline2", ""),
        "billed_at_addressline3": data.get("billed_at_addressline3", ""),
        "billed_at_branch_name": data.get("billed_at_branch_name", ""),
        "billed_at_city": data.get("billed_at_city", ""),
        "billed_at_company_name": data.get("billed_at_company_name", ""),
        "billed_at_phone_no1": data.get("billed_at_phone_no1", ""),
        "billed_at_phone_no2": data.get("billed_at_phone_no2", ""),
        "billed_at_pincode": data.get("billed_at_pincode", ""),
        "billed_at_state": data.get("billed_at_state", ""),
        "billed_at_state_code": data.get("billed_at_state_code", ""),
        "customer_GSTN_no": data.get("customer_GSTN_no", ""),
        "customer_PAN_no": data.get("customer_PAN_no", ""),
        "customer_addressline2": data.get("customer_addressline2", ""),
        "customer_addressline3": data.get("customer_addressline3", ""),
        "customer_phone_no2": data.get("customer_phone_no2", ""),
        "customer_pincode": data.get("customer_pincode", ""),
        "customer_state": data.get("customer_state", ""),
        "customer_state_code": data.get("customer_state_code", ""),
        "delivery_from_GSTN_no": data.get("delivery_from_GSTN_no", ""),
        "delivery_from_PAN_no": data.get("delivery_from_PAN_no", ""),
        "delivery_from_addressline2": data.get("delivery_from_addressline2", ""),
        "delivery_from_addressline3": data.get("delivery_from_addressline3", ""),
        "delivery_from_branch_name": data.get("delivery_from_branch_name", ""),
        "delivery_from_branch_store_code": data.get("delivery_from_branch_store_code", ""),
        "delivery_from_city": data.get("delivery_from_city", ""),
        "delivery_from_company_name": data.get("delivery_from_company_name", ""),
        "delivery_from_phone_no1": data.get("delivery_from_phone_no1", ""),
        "delivery_from_phone_no2": data.get("delivery_from_phone_no2", ""),
        "delivery_from_state": data.get("delivery_from_state", ""),
        "delivery_from_state_code": data.get("delivery_from_state_code", ""),
        "delivery_to_GSTN_no": data.get("delivery_to_GSTN_no", ""),
        "delivery_to_Name": data.get("delivery_to_Name", ""),
        "delivery_to_PAN_no": data.get("delivery_to_PAN_no", ""),
        "delivery_to_addressline1": data.get("delivery_to_addressline1", ""),
        "delivery_to_addressline2": data.get("delivery_to_addressline2", ""),
        "delivery_to_addressline3": data.get("delivery_to_addressline3", ""),
        "delivery_to_city": data.get("delivery_to_city", ""),
        "delivery_to_phone_no1": data.get("delivery_to_phone_no1", ""),
        "delivery_to_phone_no2": data.get("delivery_to_phone_no2", ""),
        "delivery_to_pincode": data.get("delivery_to_pincode", ""),
        "delivery_to_state": data.get("delivery_to_state", ""),
        "delivery_to_state_code": data.get("delivery_to_state_code", ""),
        "item_brand_name": data.get("item_brand_name", ""),
        "item_cgst": data.get("item_cgst", ""),
        "item_cgst_perc": data.get("item_cgst_perc", ""),
        "item_gross_rate": data.get("item_gross_rate", ""),
        "item_igst": data.get("item_igst", ""),
        "item_igst_perc": data.get("item_igst_perc", ""),
        "item_name": data.get("item_name", ""),
        "item_product_name": data.get("item_product_name", ""),
        "item_sgst": data.get("item_sgst", ""),
        "item_sgst_perc": data.get("item_sgst_perc", ""),
        "item_sno": data.get("item_sno", ""),
        "item_taxable_Amount": data.get("item_taxable_Amount", ""),
        "bill_cancel_amount__c": data.get("bill_cancel_amount", ""),
        "bill_cancel_date__c": data.get("bill_cancel_date", ""),
        "bill_cancel_time__c": data.get("bill_cancel_time", ""),
        "Bill_Date__c": data.get("bill_date", ""),
        "bill_grand_total__c": data.get("bill_grand_total", ""),
        "Bill_No__c": data.get("bill_no", ""),
        "bill_remarks1__c": data.get("bill_remarks1", ""),
        "bill_status__c": data.get("bill_status", ""),
        "bill_tender_type__c": data.get("bill_tender_type", ""),
        "bill_time__c": data.get("bill_time", ""),
        "bill_transaction_type__c": data.get("bill_transaction_type", ""),
        "customer_area__c": data.get("customer_area", ""),
        "customer_city__c": data.get("customer_city", ""),
        "Customer_Code_New": data.get("customer_code", ""),
        "Customer_Code__c_new": data.get("customer_code", ""),
        "Customer_Code__c": data.get("customer_code", ""),
        "customer_doa__c": data.get("customer_doa", ""),
        "customer_dob__c": data.get("customer_dob", ""),
        "customer_email__c": data.get("customer_email", ""),
        "customer_fname__c": data.get("customer_fname", ""),
        "customer_gender__c": data.get("customer_gender", ""),
        "customer_lname__c": data.get("customer_lname", ""),
        "customer_mobile__c": data.get("customer_mobile", ""),
        "customer_mobile__c_backup": data.get("customer_mobile", ""),
        "customer_mobile__c2": data.get("customer_mobile", ""),
        "item_category_name__c": data.get("item_category_name", ""),
        "Item_Code__c": data.get("item_code", ""),
        "item_gross_amount__c": data.get("item_gross_amount", ""),
        "item_net_amount__c": data.get("item_net_amount", ""),
        "item_quantity__c": data.get("item_quantity", ""),
        "item_remarks1__c": data.get("item_remarks1", ""),
        "item_remarks2__c": data.get("item_remarks2", ""),
        "item_status__c": data.get("item_status", ""),
        "item_tax__c": data.get("item_tax", ""),
        "store_code__c": data.get("store_code", "")
    }
    return mapped

record_keys = [
    "pri_id", "tid", "Id", "OwnerId", "IsDeleted", "Name", "CreatedDate",
    "CreatedById", "LastModifiedDate", "LastModifiedById", "SystemModstamp",
    "LastActivityDate", "Branch_Name__c", "Contact__c", "Customer_Number__c",
    "Customer__c", "Invoice_Amount__c", "Invoice_Date__c", "Bill_Date__c",
    "customer_mobile__c", "customerId", "Customer_Last_Name__c",
    "Customer_Name__c", "item_cgst_perc", "item_sgst_perc", "item_sgst",
    "item_igst_perc", "item_cgst", "item_igst", "Deptid",
    "billed_at_branch_name", "billed_at_company_name", "billed_at_address",
    "billed_at_city", "billed_at_state", "billed_at_phone_no1",
    "billed_at_phone_no2", "billed_at_GSTN_no", "billed_at_VAT_no",
    "billed_at_state_code", "billed_at_PAN_no", "delivery_from_branch_name",
    "delivery_from_company_name", "delivery_from_address",
    "delivery_from_city", "delivery_from_state", "delivery_from_phone_no1",
    "delivery_from_phone_no2", "delivery_from_GSTN_no",
    "delivery_from_VAT_no", "delivery_from_state_code",
    "delivery_from_PAN_no", "customer_state_code", "Email__c",
    "IMEINumber__c", "Item_Brand_Name__c", "Item_Code__c",
    "Item_Group_Name__c", "Item_Name__c", "Item_Rate__c",
    "Item_Remarks__c", "Location__c", "Product__c", "Products__c",
    "PurchasedDate__c", "Service_Center__c", "Showroom__c",
    "Showroom_code__c", "Status__c", "bill_cancel_against__c",
    "bill_cancel_amount", "bill_cancel_date__c", "bill_cancel_reason__c",
    "bill_cancel_time__c", "bill_discount__c", "bill_discount_per__c",
    "bill_grand_total__c", "bill_gross_amount__c", "bill_modify__c",
    "bill_modify_datetime__c", "bill_modify_reason__c",
    "bill_net_amount__c", "bill_remarks1__c", "bill_remarks3__c",
    "bill_remarks4__c", "bill_remarks5__c",
    "bill_round_off_amount__c", "bill_service_tax__c",
    "bill_status__c", "bill_tax__c", "bill_tender_type__c",
    "bill_time__c", "bill_transaction_no__c",
    "bill_transaction_type__c", "bill_type__c",
    "customer_address__c", "customer_area__c", "customer_city__c",
    "customer_doa__c", "customer_dob__c", "customer_email__c",
    "customer_fname__c", "customer_gender__c", "customer_lname__c",
    "customer_remarks1__c", "customer_remarks2__c",
    "customer_remarks3__c", "customer_remarks4__c",
    "customer_remarks5__c", "customer_state__c", "ext_param1__c",
    "ext_param2__c", "ext_param3__c", "ext_param4__c",
    "ext_param5__c", "item_barcode__c", "item_brand_code__c",
    "item_category_code__c", "item_category_name__c",
    "item_color_code__c", "item_color_name__c",
    "item_department_code__c", "item_department_name__c",
    "item_discount__c", "item_discount_per__c",
    "item_gross_amount__c", "item_group__c",
    "item_net_amount__c", "item_quantity__c",
    "item_remarks2__c", "item_remarks3__c",
    "item_remarks4__c", "item_remarks5__c",
    "item_serial_no__c", "item_service_tax__c",
    "item_size_code__c", "item_size_name__c",
    "item_status__c", "item_sub_category_code__c",
    "item_sub_category_name__c", "item_tax__c",
    "store_code__c", "voucher_code__c", "voucher_type__c",
    "voucher_value__c", "Docid__c", "Customer_Address_New__c",
    "customer_mobile__c_backup", "billed_at_addressline2",
    "billed_at_addressline3", "billed_at_pincode",
    "delivery_from_branch_store_code",
    "delivery_from_addressline2", "delivery_from_addressline3",
    "bill_refference_no", "bill_refference_date",
    "bill_total_trade_deduction", "bill_total_trade_addition",
    "customer_addressline2", "customer_addressline3",
    "customer_pincode", "customer_GSTN_no", "customer_PAN_no",
    "customer_state", "delivery_to_Name",
    "delivery_to_addressline1", "delivery_to_addressline2",
    "delivery_to_addressline3", "delivery_to_city",
    "delivery_to_state", "delivery_to_pincode",
    "delivery_to_phone_no1", "delivery_to_phone_no2",
    "delivery_to_GSTN_no", "delivery_to_state_code",
    "delivery_to_PAN_no", "item_sno",
    "item_name", "item_gross_rate", "item_taxable_Amount",
    "item_brand_name", "item_product_name", "customer_phone_no2",
    "updated_At", "cusId_error", "customer_mobile__c2",
    "Bill_No__c", "Customer_Code_New", "bill_modify_date",
    "bill_modify_time", "Customer_Code__c_new",
    "Customer_Code__c", "bill_remarks2", "bill_remarks2__c",
    "item_remarks1__c", "Bill_Grant_Total__c",
    "ageOfDevice", "emp_id", "emp_name"
]

up_mapping_keys = [
    "bill_modify_date", "bill_modify_time", "bill_refference_date",
    "bill_refference_no", "bill_remarks2", "bill_total_trade_addition",
    "bill_total_trade_deduction", "billed_at_GSTN_no", "billed_at_PAN_no",
    "billed_at_addressline2", "billed_at_addressline3", "billed_at_branch_name",
    "billed_at_city", "billed_at_company_name", "billed_at_phone_no1",
    "billed_at_phone_no2", "billed_at_pincode", "billed_at_state",
    "billed_at_state_code", "customer_GSTN_no", "customer_PAN_no",
    "customer_addressline2", "customer_addressline3", "customer_phone_no2",
    "customer_pincode", "customer_state", "customer_state_code",
    "delivery_from_GSTN_no", "delivery_from_PAN_no",
    "delivery_from_addressline2", "delivery_from_addressline3",
    "delivery_from_branch_name", "delivery_from_branch_store_code",
    "delivery_from_city", "delivery_from_company_name",
    "delivery_from_phone_no1", "delivery_from_phone_no2",
    "delivery_from_state", "delivery_from_state_code", "delivery_to_GSTN_no",
    "delivery_to_Name", "delivery_to_PAN_no", "delivery_to_addressline1",
    "delivery_to_addressline2", "delivery_to_addressline3", "delivery_to_city",
    "delivery_to_phone_no1", "delivery_to_phone_no2", "delivery_to_pincode",
    "delivery_to_state", "delivery_to_state_code", "item_brand_name",
    "item_cgst", "item_cgst_perc", "item_gross_rate", "item_igst",
    "item_igst_perc", "item_name", "item_product_name", "item_sgst",
    "item_sgst_perc", "item_sno", "item_taxable_Amount",
    "bill_cancel_amount__c", "bill_cancel_date__c", "bill_cancel_time__c",
    "Bill_Date__c", "bill_grand_total__c", "Bill_No__c",
    "bill_remarks1__c", "bill_status__c", "bill_tender_type__c",
    "bill_time__c", "bill_transaction_type__c", "customer_area__c",
    "customer_city__c", "Customer_Code_New", "Customer_Code__c_new",
    "Customer_Code__c", "customer_doa__c", "customer_dob__c",
    "customer_email__c", "customer_fname__c", "customer_gender__c",
    "customer_lname__c", "customer_mobile__c", "customer_mobile__c_backup",
    "customer_mobile__c2", "item_category_name__c", "Item_Code__c",
    "item_gross_amount__c", "item_net_amount__c", "item_quantity__c",
    "item_remarks1__c", "item_remarks2__c", "item_status__c",
    "item_tax__c", "store_code__c"
]